### ISSUE TITLE
Total blocks not equally Pending + Confirmed +Orphaned

### ISSUE THREAD

**Issue by ghost** [krisklosterman/node-open-mining-portal#4] opened 2017-08-23 08:35 UTC
Total blocks not equally Pending + Confirmed +Orphaned
Is it notmal?
![blocks](https://user-images.githubusercontent.com/12374549/29606500-282be96e-87f7-11e7-9fda-eeb52aa49361.PNG)

**Comment by krisklosterman** [comment] 2017-08-24 12:56
@foxer666 run these commands

```
redis-cli

scard aircoin:blocksConfirmed
scard aircoin:blocksKicked
scard aircoin:blocksOrphaned
scard aircoin:blocksPending
```
paste results here please

**Comment by ghost** [comment] 2017-08-24 13:53
@krisklosterman 
```
root@mining:~# redis-cli
127.0.0.1:6379> scard aircoin:blocksConfirmed
(integer) 82
127.0.0.1:6379> scard aircoin:blocksKicked
(integer) 70
127.0.0.1:6379> scard aircoin:blocksOrphaned
(integer) 0
127.0.0.1:6379> scard aircoin:blocksPending
(integer) 0
127.0.0.1:6379>
```
Blocks in web interface is null.
![image](https://user-images.githubusercontent.com/12374549/29669596-af48cc82-88ec-11e7-8fef-794e6048f6a0.png)

**Comment by krisklosterman** [comment] 2017-08-24 14:07
82 + 70 = 152 (You have 70 blocks that were kicked)

**Comment by ghost** [comment] 2017-08-24 14:18
@krisklosterman 
It can not work in auto mode?

**Comment by ghost** [comment] 2017-08-24 14:19
@krisklosterman 
We hav many questions and WHAT-TO-DO fo NOMP. How can we work with it?

**Comment by krisklosterman** [comment] 2017-09-28 20:09
Closing this as this was not a bug, kicked blocks were just not displayed on the webpage.

**Closed as completed by krisklosterman** 2017-09-28 20:09 UTC
